version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: ${DOCKER_REGISTRY}/example_server
    ports:
      - 3000
    volumes:
      - ../src:/opt/app/src
      - ../tsconfig.json:/opt/app/tsconfig.json
      - ../package.json:/opt/app/package.json
      - ../package-lock.json:/opt/app/package-lock.json
    hostname: ansible
    networks:
      webproxy-network:
        aliases:
          - ansible

networks:
  webproxy-network:
    external: true
